---
title: "What's in a name?"
author: "Your name"
date: "Today's date"
output: html_document
---

```{r echo = FALSE}
# Exercise 2: Modify this file to use an interactive dygraph to display `all`. Notice that the dygraph can do something plot cannot; it can display the predictions and the error band alongside the original time series. Include a range selector and useful labels.

# You can model your dygraph code after the code at 
# http://rstudio.github.io/dygraphs/gallery-upper-lower-bars.html
# http://rstudio.github.io/dygraphs/gallery-range-selector.html

# Delete this code chunk in your final document.
```

```{r echo=FALSE, message=FALSE}
library(reportsWS)
library(forecast)

# Select name and gender
name <- "Gillian"    # Always capitalize
sex <- "F"           # or "M"
names <- get_babyname(name, sex)

# Create time series and forecast
nbirths <- ts(names$n, start = 1880)
mod <- auto.arima(nbirths)
pred <- forecast(mod, h = 12) # 12 for 2025
```

Since 1880, `r sum(nbirths, na.rm = TRUE)` children have been named **`r name`**. The graph below breaks this number down by year showing the number of children named `r name` as a time series. 

```{r echo = FALSE, warning = FALSE}
# Make plot
title <- paste0("Number of children named ", name)
all <- bind_as_xts(nbirths, pred) 
plot(all, main = title)
```

We modeled this time series with an `r trim_whitespace(pred$method)` model to predict the number of children that will be given the name `r name` in 2025.

```{r echo = FALSE}
knitr::kable(data.frame(
  method = trim_whitespace(pred$method), 
  predicted_2025 = round(xts::last(pred$mean))), "markdown")
```

