---
title: "Solution 4 - YAML headers"
output: 
  html_document:
    toc: true
    number_sections: true
    theme: spacelab
---

Modify the YAML of this document to add:

1. A table of contents (toc).
2. Numbered sections (number_sections). 
3. A new theme (theme). Use one of R Markdowns prepackaged themes: `default`, `cerulean`, `journal`, `flatly`, `readable`, `spacelab`, `united`, `cosmo`.

Re-render the document after each step.

# YAML

Customize the render process of your _.Rmd_ file with YAML header. A YAML header is a section of `key: value` pairs surrounded by `---` marks.

## output:

The `output:` key determines which type of file to build when you call `rmarkdown::render()`.

### options

R Markdown comes with seven basic output formats:

1. `html_document`
2. `pdf_document`
3. `word_document` 
4. `md_document`  
5. `ioslides_presentation`  
6. `slidy_presentation`  
7. `beamer_presentation`  

### suboptions

Each output option also takes sub options. Use `args` to see which output options a format recognizes:

```{r}
args(rmarkdown::html_document)
```